version: '3.2'
services:
    db:
        image: mariadb/server
        volumes:
            - type: volume
              source: db
              target: /var/lib/mysql
            - ./app/src/installation/tables.my.sql:/docker-entrypoint-initdb.d/01-init-data.sql:ro
        environment:
            MARIADB_RANDOM_ROOT_PASSWORD: 'true'
            MARIADB_DATABASE: ${DB_NAME}
            MARIADB_USER: ${DB_USER}
            MARIADB_PASSWORD: ${DB_PASSWORD}
        restart: unless-stopped
    app:
        build: ./app
        links:
            - db
        volumes:
            - type: volume
              source: app_files
              target: /var/www/html
        depends_on:
            - db
        environment:
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            LANG: fr_FR.UTF-8
            LANGUAGE: fr_FR:en
            LC_ALL: fr_FR.UTF-8
        restart: unless-stopped
    web:
        build: ./web
        links:
            - app
        volumes:
            - type: volume
              source: app_files
              target: /var/www/html
              volume:
                nocopy: true
        ports:
            - "${EXTERNAL_PORT}:80"
        depends_on:
            - app
        restart: unless-stopped
volumes:
    db:
    app_files:
